### ISSUE TITLE
html-webpack-plugin isnt adding the ddl to html

### ISSUE THREAD

**Issue by henningborchers** [clinyong/dll-link-webpack-plugin#15]
Your example doesnt add the ddl to the html.
There are no errors in the build and it successfully outputs:
[dll-link-plugin]: Rebuilding dll.

I am working with the following versions:

"html-webpack-plugin": "3.2.0",
"webpack": "4.6.0",
"dll-link-webpack-plugin": "3.0.2"

**Comment by clinyong** [comment]
Fix at <https://github.com/clinyong/dll-link-webpack-plugin/commit/32e3510fe16feb7a9876fcadd9b152475b326ec0>. Please pull the latest code and reinstall package. If you still meet problem, let me know it.

**Comment by henningborchers** [comment]
Thanks! Now it works!
