### ISSUE TITLE
Is this project related to webpack-dll-bundles-plugin?

### ISSUE THREAD

**Issue by Li0liQ** [clinyong/dll-link-webpack-plugin#2]
Is this project related to https://github.com/shlomiassaf/webpack-dll-bundles-plugin ?
If not, I guess, you can cooperate and share ideas :).

**Comment by clinyong** [comment]
Both of these build dll files, may be that's the only same part :-)

I do not actually use `dll-bundles-plugin` in real project, but compare to it's readme, `dll-link-plugin` 

- use a independent dll config file. It is more easy to debug. And if someday you won't use this plugin, just replace it with `DllReferencePlugin`
- use cache. If your dll libs do not change, no need to rebuild the dll file
- auto include dll file in your output html if you are using `html-webpack-plugin `
- use `yarn.lock`  to check libs dependency. So if you don't use yarn, you can't use this plugin. But l will support `npm.lock` laterly
